default_platform(:ios)

platform :ios do
  desc "Create/refresh profiles & certificates for FreeAPS"
  lane :certs do
    setup_ci if ENV['CI']   # ← 必须加！

    api_key = app_store_connect_api_key(
      key_id: ENV['FASTLANE_KEY_ID'],
      issuer_id: ENV['FASTLANE_ISSUER_ID'],
      key_filepath: "fastlane/AuthKey.p8"
    )

    app_ids = [
      "ru.artpancreas.#{ENV['TEAMID']}.FreeAPS",
      "ru.artpancreas.#{ENV['TEAMID']}.FreeAPS.watchkitapp",
      "ru.artpancreas.#{ENV['TEAMID']}.FreeAPS.watchkitapp.watchkitextension"
    ]

    match(
      type: "appstore",
      app_identifier: app_ids,
      readonly: false,
      api_key: api_key
    )
  end


  desc "Build FreeAPS X and upload to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']   # ← 必须加！

    api_key = app_store_connect_api_key(
      key_id: ENV['FASTLANE_KEY_ID'],
      issuer_id: ENV['FASTLANE_ISSUER_ID'],
      key_filepath: "fastlane/AuthKey.p8"
    )

    sh "echo '===== BUNDLE ID DEBUG INFO ====='"
    sh "echo 'TEAMID: #{ENV['TEAMID']}'"
    sh "echo 'FreeAPS: ru.artpancreas.#{ENV['TEAMID']}.FreeAPS'"
    sh "echo 'WatchApp: ru.artpancreas.#{ENV['TEAMID']}.FreeAPS.watchkitapp'"
    sh "echo 'WatchExt: ru.artpancreas.#{ENV['TEAMID']}.FreeAPS.watchkitapp.watchkitextension'"
    sh "echo '================================='"

    app_ids = [
      "ru.artpancreas.#{ENV['TEAMID']}.FreeAPS",
      "ru.artpancreas.#{ENV['TEAMID']}.FreeAPS.watchkitapp",
      "ru.artpancreas.#{ENV['TEAMID']}.FreeAPS.watchkitapp.watchkitextension"
    ]

    match(
      type: "appstore",
      app_identifier: app_ids,
      readonly: true,
      api_key: api_key
    )

    build_app(
      workspace: "FreeAPS.xcworkspace",
      scheme: "FreeAPS X",
      configuration: "Release",
      export_method: "app-store",
      export_team_id: ENV['TEAMID'],
      xcargs: "-allowProvisioningUpdates SKIP_WATCH_COMPILE=YES"
    )

    upload_to_testflight(
      api_key: api_key
    )
  end
end
