default_platform(:ios)

platform :ios do
  desc "Build FreeAPS X and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV['FASTLANE_KEY_ID'],
      issuer_id: ENV['FASTLANE_ISSUER_ID'],
      key_filepath: "fastlane/AuthKey.p8"
    )

    build_app(
      workspace: "FreeAPS.xcworkspace",
      scheme: "FreeAPS",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key
    )
  end
end
